// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVC_Project.Models;

public partial class Chat
{
    public int ChatID { get; set; }

    public int? ActivityID { get; set; }

    public int? UserID { get; set; }

    public string ChatContent { get; set; }

    public int? ToWhom { get; set; }

    public DateTime? ChatTime { get; set; }

    public virtual Group Activity { get; set; }

    public virtual ICollection<Chat> InverseToWhomNavigation { get; set; } = new List<Chat>();

    public virtual Chat ToWhomNavigation { get; set; }

    public virtual Member User { get; set; }
}