// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVC_Project.Models;

public partial class Contact
{
    public int FormID { get; set; }

    public string SenderName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string EmailTitle { get; set; }

    public string FormContent { get; set; }

    public DateTime? SendTime { get; set; }
}