// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Humanizer.Localisation;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC_Project.Models;

public partial class Group
{
    public int GroupID { get; set; }

    [Required(ErrorMessage = "活動名稱為必填項")]
    public string GroupName { get; set; }

    public string GroupCategory { get; set; }

    public string GroupContent { get; set; }

    [Range(3, int.MaxValue, ErrorMessage = "人數下限最少3人")]
    public int? MinAttendee { get; set; }

    public int? MaxAttendee { get; set; }

    [Required(ErrorMessage = "請選擇活動起始日")]
    public DateTime? StartDate { get; set; }

    [Required(ErrorMessage = "請選擇活動結束日")]
    public DateTime? EndDate { get; set; }

    public int? Organizer { get; set; }

    public int? OriginalActivityID { get; set; }

    public bool HasSent { get; set; }   //10/19新增，確保不會重複寄送轉為"報名中"活動通知

    public virtual ICollection<Chat> Chat { get; set; } = new List<Chat>();

    public virtual Member OrganizerNavigation { get; set; }

    public virtual MyActivity OriginalActivity { get; set; }

    public virtual ICollection<PersonalPhoto> PersonalPhoto { get; set; } = new List<PersonalPhoto>();

    public virtual ICollection<Registration> Registration { get; set; } = new List<Registration>();
}