// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVC_Project.Models;

public partial class VoteRecord
{
    public int RecordID { get; set; }

    public int? UserID { get; set; }

    public int? ActivityID { get; set; }

    public DateTime? VoteResult { get; set; }

    public virtual MyActivity Activity { get; set; }

    public virtual Member User { get; set; }
}